apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  type: LoadBalancer  # LoadBalancer로 외부 액세스를 허용
  ports:
    - protocol: TCP
      port: 80        # 외부에서 접근할 서비스 포트
      targetPort: 5000 # 컨테이너 내부의 Flask 포트
